# Generated by Django 5.0.4 on 2024-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='professional_roles',
            new_name='key_skills',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
