# Generated by Django 5.0.4 on 2024-04-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_way_status_alter_psychotest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='account',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='way',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='way',
            name='test_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ways', to='api.testtask'),
        ),
        migrations.AlterField(
            model_name='way',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
