# Generated by Django 5.0.4 on 2024-04-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_event_account_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='sent_to_director',
            field=models.BooleanField(default=False),
        ),
    ]
