# Generated by Django 5.0.4 on 2024-04-14 08:15

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_way_sent_to_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default=api.utils.generate_login, max_length=100, unique=True),
        ),
    ]
