version: "3.3"

services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db

  frontend:
    build: frontend
    volumes:
      - ./build:/app/build

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./build:/var/www/build
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  static:
  media:
  build:
  data: